import { execFile } from "child_process";
import { promisify } from "util";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import { v4 as uuidv4 } from "uuid";
import type { FileChange, PlanStep, WorkflowState } from "./types";

const execFileAsync = promisify(execFile);

export interface SafeOperationResult {
  startingCommit: string;
  modernizationCommit: string;
  filesChanged: FileChange[];
}

function oneLine(value: string): string {
  return value.replace(/[\r\n|]+/g, " ").trim();
}

function buildRepositoryReadme(state: WorkflowState, baseline: string): string {
  const structure = state.repository.projectStructure.length > 0
    ? state.repository.projectStructure.map((entry) => `- \`${oneLine(entry.path)}\` (${entry.kind === "directory" ? `${entry.files} source files` : "manifest/documentation"})`).join("\n")
    : "- Project structure was not detected during static analysis.";

  return [
    `# ${oneLine(state.repository.name)}`,
    "",
    "Repository context generated by Legacy Code Whisperer from static analysis.",
    "",
    `- Repository: ${oneLine(state.repository.url)}`,
    `- Branch: ${oneLine(state.repository.branch)}`,
    `- Baseline commit: \`${baseline}\`` ,
    `- Language: ${oneLine(state.repository.language)}`,
    `- Framework: ${oneLine(state.repository.framework)}`,
    `- Runtime: ${oneLine(state.repository.runtime)}`,
    `- Package manager: ${oneLine(state.repository.packageManager)}`,
    `- Source files: ${state.repository.files}`,
    `- Estimated lines of code: ${state.repository.linesOfCode}`,
    "",
    "## Detected structure",
    "",
    structure,
    "",
    "This file was added in an isolated workflow workspace. No remote repository was modified or pushed.",
    "",
  ].join("\n");
}

export async function executeApprovedOperation(
  workspace: string,
  state: WorkflowState,
  step: PlanStep,
): Promise<SafeOperationResult> {
  if (step.operationId !== "create-analysis-readme") {
    throw new Error("This plan step has no registered safe operation.");
  }

  const readmePath = path.join(workspace, "README.md");
  const legacyReadmePath = path.join(workspace, "README");
  if (fs.existsSync(readmePath) || fs.existsSync(legacyReadmePath)) {
    throw new Error("README creation is no longer applicable because a root README already exists.");
  }

  const { stdout: baselineOutput } = await execFileAsync("git", ["rev-parse", "HEAD"], { cwd: workspace });
  const startingCommit = baselineOutput.trim();
  if (!startingCommit.startsWith(state.repository.currentCommit)) {
    throw new Error("The retained workspace HEAD no longer matches the analyzed baseline commit.");
  }
  const { stdout: dirtyOutput } = await execFileAsync("git", ["status", "--porcelain"], { cwd: workspace });
  if (dirtyOutput.trim()) throw new Error("The retained workspace is not clean; safe execution was refused.");

  const hooksPath = fs.mkdtempSync(path.join(os.tmpdir(), "lcw-hooks-"));
  const globalConfig = path.join(os.tmpdir(), `lcw-empty-git-config-${uuidv4()}`);
  fs.writeFileSync(globalConfig, "", "utf8");
  const gitOptions = {
    cwd: workspace,
    windowsHide: true,
    env: { ...process.env, GIT_CONFIG_NOSYSTEM: "1", GIT_CONFIG_GLOBAL: globalConfig },
  };
  try {
    fs.writeFileSync(readmePath, buildRepositoryReadme(state, startingCommit), { encoding: "utf8", flag: "wx" });
    await execFileAsync("git", ["add", "--", "README.md"], gitOptions);
    await execFileAsync("git", [
      "-c", "user.name=Legacy Code Whisperer",
      "-c", "user.email=legacy-code-whisperer@localhost",
      "-c", `core.hooksPath=${hooksPath}`,
      "-c", "commit.gpgsign=false",
      "commit", "-m", "docs(workflow): add analyzed repository summary",
    ], { ...gitOptions, timeout: 60_000 });
  } finally {
    fs.rmSync(hooksPath, { recursive: true, force: true });
    fs.rmSync(globalConfig, { force: true });
  }

  const { stdout: headOutput } = await execFileAsync("git", ["rev-parse", "HEAD"], { cwd: workspace });
  const modernizationCommit = headOutput.trim();
  const { stdout: numstat } = await execFileAsync("git", ["show", "--format=", "--numstat", modernizationCommit], { cwd: workspace });
  const filesChanged = numstat.trim().split(/\r?\n/).filter(Boolean).map((line) => {
    const [added, deleted, file] = line.split("\t");
    return { file, additions: Number(added), deletions: Number(deleted) };
  });
  return { startingCommit, modernizationCommit, filesChanged };
}