import { repoInfo, safetyNet, overallProgress, planSteps } from "../mockData";

function ProgressBar({ value }: { value: number }) {
  return (
    <div style={{ background: "var(--surface-2)", borderRadius: 4, height: 8, overflow: "hidden" }}>
      <div
        style={{
          width: `${value}%`,
          height: "100%",
          background: "linear-gradient(90deg, var(--accent) 0%, var(--purple) 100%)",
          borderRadius: 4,
          transition: "width 0.6s ease",
        }}
      />
    </div>
  );
}

function SafetyNetBadge() {
  const allPass = safetyNet.failing === 0;
  return (
    <div
      style={{
        display: "flex",
        alignItems: "center",
        gap: 12,
        padding: "14px 18px",
        background: allPass ? "#23863622" : "var(--red-dim)",
        border: `1px solid ${allPass ? "#23863655" : "#da363355"}`,
        borderRadius: "var(--radius)",
      }}
    >
      <span style={{ fontSize: 24 }}>{allPass ? "✓" : "✗"}</span>
      <div>
        <div style={{ fontWeight: 700, color: allPass ? "var(--green)" : "var(--red)", fontSize: 16 }}>
          Safety Net: {safetyNet.passing}/{safetyNet.total} tests passing
        </div>
        <div style={{ color: "var(--muted)", fontSize: 12, marginTop: 2 }}>
          Generated by {safetyNet.generatedBy}
        </div>
      </div>
    </div>
  );
}

function StepMini({ step }: { step: (typeof planSteps)[0] }) {
  const icon =
    step.status === "completed"
      ? { symbol: "✓", color: "var(--green)" }
      : step.status === "executing"
      ? { symbol: "⟳", color: "var(--yellow)" }
      : step.status === "failed"
      ? { symbol: "✗", color: "var(--red)" }
      : { symbol: "○", color: "var(--muted)" };

  return (
    <div
      style={{
        display: "flex",
        alignItems: "center",
        gap: 10,
        padding: "8px 0",
        borderBottom: "1px solid var(--border)",
        opacity: step.status === "pending" ? 0.55 : 1,
      }}
    >
      <span style={{ color: icon.color, fontSize: 14, width: 16, textAlign: "center", flexShrink: 0 }}>
        {icon.symbol}
      </span>
      <span style={{ flex: 1, color: step.status === "executing" ? "var(--yellow)" : "var(--text)" }}>
        Step {step.id} — {step.title}
      </span>
      {step.testsDelta && (
        <span className="mono" style={{ color: step.status === "completed" ? "var(--green)" : "var(--muted)" }}>
          {step.testsDelta}
        </span>
      )}
    </div>
  );
}

export default function OverviewScreen({ repoUrl }: { repoUrl?: string | null }) {
  const completed = planSteps.filter((s) => s.status === "completed").length;
  const executing = planSteps.find((s) => s.status === "executing");

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 20 }}>
      {/* Header */}
      <div>
        <h2 style={{ fontSize: 22, fontWeight: 700, marginBottom: 4 }}>Project Overview</h2>
        <p style={{ color: "var(--muted)" }}>
          Live status of the Legacy Code Whisperer modernization session
        </p>
      </div>

      {/* Safety net — hero */}
      <SafetyNetBadge />

      {/* Repo + Progress row */}
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16 }}>
        {/* Repo card */}
        <div className="card">
          <div className="section-title">Legacy Repository</div>
          <div style={{ fontSize: 16, fontWeight: 700, marginBottom: 4 }}>{repoInfo.name}</div>
          {repoUrl && (
            <div className="mono" style={{ fontSize: 11, color: "var(--accent)", marginBottom: 10, wordBreak: "break-all" }}>
              {repoUrl}
            </div>
          )}
          <table style={{ width: "100%", borderCollapse: "collapse" }}>
            {[
              ["Runtime", repoInfo.runtime],
              ["Framework", repoInfo.framework],
              ["Language", repoInfo.language],
              ["Last Commit", repoInfo.lastCommit],
              ["Files", repoInfo.files.toString()],
              ["Lines of Code", repoInfo.linesOfCode.toLocaleString()],
            ].map(([label, value]) => (
              <tr key={label} style={{ borderBottom: "1px solid var(--border)" }}>
                <td style={{ padding: "6px 0", color: "var(--muted)", width: "40%" }}>{label}</td>
                <td style={{ padding: "6px 0", fontWeight: 500 }}>{value}</td>
              </tr>
            ))}
          </table>
        </div>

        {/* Progress card */}
        <div className="card" style={{ display: "flex", flexDirection: "column", gap: 16 }}>
          <div className="section-title">Modernization Progress</div>
          <div style={{ textAlign: "center", padding: "16px 0" }}>
            <div style={{ fontSize: 52, fontWeight: 800, color: "var(--accent)", lineHeight: 1 }}>
              {overallProgress}%
            </div>
            <div style={{ color: "var(--muted)", marginTop: 8 }}>
              {completed} of {planSteps.length} steps complete
            </div>
          </div>
          <ProgressBar value={overallProgress} />
          {executing && (
            <div
              style={{
                padding: "10px 14px",
                background: "#9e6a0322",
                border: "1px solid #9e6a0355",
                borderRadius: "var(--radius)",
                fontSize: 13,
              }}
            >
              <span style={{ color: "var(--yellow)", fontWeight: 600 }}>Now executing: </span>
              {executing.title}
            </div>
          )}
        </div>
      </div>

      {/* Plan mini */}
      <div className="card">
        <div className="section-title">Modernization Steps</div>
        {planSteps.map((s) => (
          <StepMini key={s.id} step={s} />
        ))}
      </div>
    </div>
  );
}
